name = "bing"
main = "src/index.js"
compatibility_date = "2024-01-01"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BING_KV"
id = "your-kv-namespace-id"

[triggers]
crons = ["5 16 * * *"]
