name = "bing"
main = "src/index.js"
compatibility_date = "2024-01-01"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BING_KV"
id = "your-kv-namespace-id"

[triggers]
crons = ["5 16 * * *"]

[vars]
# BING_API = "https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN"
